# Generated by Django 5.1.7 on 2025-10-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='companies_placed',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='highest_slab_placed',
            field=models.IntegerField(choices=[(0, 'Not Placed'), (1, 'Slab 1 (<6 LPA)'), (2, 'Slab 2 (6–12 LPA)'), (3, 'Slab 3 (>=12 LPA)')], default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='offers_received',
            field=models.IntegerField(default=0),
        ),
    ]
