# Generated by Django 5.1.7 on 2025-10-04 06:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('ctc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('slab', models.IntegerField(blank=True, choices=[(1, 'Slab 1 (< 6 LPA)'), (2, 'Slab 2 (6–12 LPA)'), (3, 'Slab 3 (>= 12 LPA)')], null=True)),
                ('deadline', models.DateTimeField()),
                ('min_cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('max_backlogs', models.IntegerField(default=0)),
                ('history_allowed', models.BooleanField(default=True)),
                ('jd_file', models.FileField(upload_to='job_descriptions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_open', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], default='Applied', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'unique_together': {('student', 'job')},
            },
        ),
    ]
