# Generated by Django 5.1.7 on 2025-10-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_open',
        ),
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('open', 'Applications Open'), ('progress', 'In Progress'), ('closed', 'Completed')], default='open', max_length=20),
        ),
    ]
