# Generated by Django 5.1.7 on 2025-10-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_is_open_job_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='jd_file',
            field=models.FileField(blank=True, null=True, upload_to='job_descriptions/'),
        ),
    ]
