# Generated by Django 5.1.7 on 2025-10-11 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_jd_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='recruitment_updates',
            field=models.TextField(blank=True, default='Applications are currently open.'),
        ),
    ]
